version: '2'
services:
    redis:
        image: "redis"
        volumes:
          - ./redis/data:/data
        ports:
          - "127.0.0.1:6379:6379"

    driver:
        build: ./verlichting/my_node_openzwave
        links:
          - redis:redis
        volumes:
          - ../driver/config/config.json:/etc/config.json:ro
          - ../driver/log:/root/my_node_openzwave/log
        environment:
          - REDIS_HOST=redis
        depends_on:
          - redis

    webapp:
        build: ./verlichting/webapp
        links:
          - redis:redis
          - driver:driver
        environment:
          - UPSTREAM_SERVER_HOST=driver
          - UPSTREAM_SERVER_PORT=3000
          - RACK_ENV=development
          - REDIS_URL=redis://redis:6379/
        volumes:
          - ../webapp/.env:/root/verlichting-webapp/.env:ro
        depends_on:
          - driver
    freshrss:
        build: ./freshrss
        volumes:
          - freshrss_data:/var/www/html/data
    bookstack:
        image: "solidnerd/bookstack"
        environment:
          - DB_HOST=bookstack_db
          - DB_DATABASE=bookstack
          - DB_USER=bookstack
        depends_on:
          - bookstack_db
    bookstack_db:
        image: "mysql:5.7.21"
        environment:
          - MYSQL_DATABASE=bookstack
          - MYSQL_USER=bookstack

    nginx:
        image: nginx:1.13.9
        links:
          - webapp:webapp
        volumes:
          - ../../verlichting/elm/out:/var/www/verlichting-static:ro
volumes:
    freshrss_data:
