version: '2'

services:
    driver:
        devices:
          - /dev/ttyUSB0:/dev/ttyUSB0
        command: node main.js --live --config /etc/config.json
    webapp:
        environment:
          - RACK_ENV=production
    nginx:
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - ../nginx/conf.d:/etc/nginx/conf.d
          - /var/docker/openzwave/www:/var/www/verlichting
          - /var/www/challenges:/var/www/challenges
          - ../nginx/certs:/certs
