version: '2'

services:
    redis:
        restart: unless-stopped
    driver:
        devices:
          - /dev/ttyUSB0:/dev/ttyUSB0
        command: yarn start --live --config /etc/config.json
        restart: unless-stopped
    webapp:
        environment:
          - RACK_ENV=production
        restart: unless-stopped
    nginx:
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - ../nginx/conf.d:/etc/nginx/conf.d:ro
          - /var/docker/openzwave/www:/var/www/verlichting-static:ro
          - /var/docker/energie/www:/var/www/energie-static:ro
          - /var/www/challenges:/var/www/challenges:ro
          - ../nginx/certs:/certs:ro
        restart: unless-stopped
    bookstack:
        env_file:
          - /var/docker/bookstack/.env
        restart: unless-stopped
    bookstack_db:
        env_file:
          - /var/docker/bookstack/.env
        volumes:
          - /var/docker/bookstack:/var/lib/mysql
        restart: unless-stopped
    tt-rss:
        restart: unless-stopped
    tt-rss-db:
        env_file:
          - /var/docker/tt-rss/.env
        volumes:
          - /var/docker/tt-rss/data:/var/lib/postgresql/data
        restart: unless-stopped
    tt-rss-updater:
        restart: unless-stopped
