version: '2'
services:
    redis:
        image: "redis"
        volumes:
          - ./redis/data:/data

    driver:
        build: ./my_node_openzwave
        links:
          - redis:redis
        volumes:
          - ./my_node_openzwave/config.json:/etc/config.json
          - ./my_node_openzwave/log:/root/my_node_openzwave/log
        environment:
          - REDIS_HOST=redis
        depends_on:
          - redis

    webapp:
        build: ./verlichting-webapp
        links:
          - redis:redis
          - driver:driver
        environment:
          - UPSTREAM_SERVER_HOST=driver
          - UPSTREAM_SERVER_PORT=3000
          - RACK_ENV=development
          - REDIS_URL=redis://redis:6379/
        volumes:
          - ./verlichting-webapp/log:/root/verlichting-webapp/log
        depends_on:
          - driver
    nginx-verlichting:
        image: nginx:1.13.9
        ports:
          - "8080:80"
        links:
          - webapp:webapp
        volumes:
          - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
          - /var/www/verlichting:/var/www/verlichting
