version: '2'
services:
    redis:
        image: "redis"
        volumes:
          - ./redis/data:/data

    driver:
        build: ./my_node_openzwave
        links:
          - redis:redis
        volumes:
          - ../driver/config/config.json:/etc/config.json
          - ../driver/log:/root/my_node_openzwave/log
        environment:
          - REDIS_HOST=redis
        depends_on:
          - redis

    webapp:
        build: ./verlichting-webapp
        links:
          - redis:redis
          - driver:driver
        environment:
          - UPSTREAM_SERVER_HOST=driver
          - UPSTREAM_SERVER_PORT=3000
          - RACK_ENV=development
          - REDIS_URL=redis://redis:6379/
        volumes:
          - ./webapp/log:/root/verlichting-webapp/log
          - ./webapp/dotenv:/root/verlichting-webapp/.env
        depends_on:
          - driver
    nginx:
        image: nginx:1.13.9
        ports:
          - "8080:80"
        links:
          - webapp:webapp
        volumes:
          - ../../verlichting/elm/out:/var/www/verlichting
