version: '3'

services:
    redis:
        restart: unless-stopped
    driver:
        devices:
          - /dev/ttyUSB0:/dev/ttyUSB0
        command: yarn start --live --config /etc/config.json
        environment:
          - TZ=Europe/Amsterdam
        restart: unless-stopped
    webapp:
        environment:
          - RACK_ENV=production
          - TZ=Europe/Amsterdam
        restart: unless-stopped
