version: '2'

# These are the development overrides for the application
services:
    driver:
        command: yarn start --config /etc/config.json
    nginx:
        ports:
          - "8000:80"
        volumes:
          - ../nginx/conf.d:/etc/nginx/conf.d:ro
          - /var/docker/openzwave/www:/var/www/verlichting-static:ro
          - /var/docker/energie/www:/var/www/energie-static:ro
          - /var/www/challenges:/var/www/challenges:ro
          - ../nginx/certs:/certs:ro
    webapp:
        environment:
          - RACK_ENV=development
        ports:
          - "8001:3000"
    bookstack:
        ports:
          - "8002:80"
        environment:
          - DB_PASSWORD=bookstack
          - MYSQL_ROOT_PASSWORD=root_password
    bookstack_db:
        environment:
          - MYSQL_PASSWORD=bookstack
          - MYSQL_ROOT_PASSWORD=root_password
    tt-rss:
        ports:
          - "80:80"
    tt-rss-db:
        environment:
          - POSTGRES_USER=tt-rss
          - POSTGRES_PASSWORD=tt-rss
          - POSTGRES_DB=tt-rss
    nextcloud:
        ports:
          - "8080:80"
        volumes:
          - ../nextcloud/:/var/www/html
