version: '2'

services:
    redis:
        restart: unless-stopped
    driver:
        devices:
          - /dev/ttyUSB0:/dev/ttyUSB0
        command: node main.js --live --config /etc/config.json
        restart: unless-stopped
    webapp:
        environment:
          - RACK_ENV=production
        restart: unless-stopped
    freshrss:
        volumes:
          - /var/docker/freshrss:/var/www/html/data
    nginx:
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - ../nginx/conf.d:/etc/nginx/conf.d:ro
          - /var/docker/openzwave/www:/var/www/verlichting-static:ro
          - /var/docker/energie/www:/var/www/energie-static:ro
          - /var/www/challenges:/var/www/challenges:ro
          - ../nginx/certs:/certs:ro
        restart: unless-stopped
