version: '2'
services:
    redis:
        image: "redis"
        volumes:
          - ./redis/data:/data
        ports:
          - "127.0.0.1:6379:6379"

    driver:
        build: ./my_node_openzwave
        links:
          - redis:redis
        volumes:
          - ../driver/config/config.json:/etc/config.json:ro
          - ../driver/log:/root/my_node_openzwave/log
        environment:
          - REDIS_HOST=redis
        depends_on:
          - redis

    webapp:
        build: ./webapp
        links:
          - redis:redis
          - driver:driver
        environment:
          - UPSTREAM_SERVER_HOST=driver
          - UPSTREAM_SERVER_PORT=3000
          - RACK_ENV=development
          - REDIS_URL=redis://redis:6379/
        volumes:
          - ../webapp/.env:/root/verlichting-webapp/.env:ro
        depends_on:
          - driver
    nginx:
        image: nginx:1.13.9
        links:
          - webapp:webapp
        volumes:
          - ../../verlichting/elm/out:/var/www/verlichting-static:ro
